### PR TITLE
Update compatibility for ultraliser v0.4.0

### PR DESCRIPTION
**Pull request by asoplata**
This makes the necessary changes for placement-hints' mesh creation to use the current version of Ultraliser, v0.4.0

### CODE REVIEW

**Comment by asoplata** [comment]
I tried beginning to run the tests, and unfortunately updating the tests for ultraliser v0.4.0 will likely be a significant pain: it seems the tests are hardcoded to use ultraliser v0.1.0 ( https://github.com/BlueBrain/atlas-placement-hints/blob/main/tests/distances/test_create_watertight_mesh.py#L19 ), and I know for a fact that ultraliser has gone through breaking changes across its versions.

**Comment by asoplata** [comment]
The tests begin to fail when transitioning from ultraliser v0.3.0 (available in archive/2022-05, among others) to ultraliser v0.4.0. Simply changing the location of the executable causes the tests to fail. One cause of this is almost certainly because the filenames/formats that `ultraVolume2Mesh` expects seem to have changed when moving to v0.4.0, which is part of what I had to change in the commit in this PR.

**Comment by asoplata** [comment]
Don't worry about this PR for now -- see https://github.com/BlueBrain/atlas-placement-hints/pull/11#issuecomment-1717238503

**Comment by arnaudon** [comment]
I've done it in #18

**Comment by arnaudon** [comment]
I guess we can close this one then?

**Comment by mgeplf** [comment]
yup, fine on my end, @asoplata?

**Comment by asoplata** [comment]
Sure

**Pull request closed without merging**
