### PR TITLE
new regex with barrel cortex barrel names exception

### PR DESCRIPTION
**Pull request by alTeska**
as discussed:  https://github.com/BlueBrain/atlas-commons/pull/5 

For layers 6a and 6b the regex still keeps the `6[ab]` part, the rest is removed. 

Uncertain why the original layer 3 regex had additional symbols: `[^/]3`, am I missing something?

### CODE REVIEW

**Comment by lecriste** [comment]
OK. Can I rerun the Atlas pipeline with this new version of `isocortex_metadata.json`?

**Comment by alTeska** [comment]
For me, yes!

**Comment by mgeplf** [comment]
Was the pipeline rerun w/ this @lecriste?
If so, we can work on getting CI to pass, and get it merged.

**Comment by lecriste** [comment]
Not yet.

**Comment by rai-pranav** [comment]
Vishal and I , had looked at this issue, and what we found was that the issue with the earlier regexes could be potentially be resolved by setting `"with_descendants": false` within `layers` element in the `isocortex_metadata.json` .  What is the rationale for `"with_descendants": true` in the current code?

**Comment by lecriste** [comment]
> Vishal and I , had looked at this issue, and what we found was that the issue with the earlier regexes could be potentially be resolved by setting `"with_descendants": false` within `layers` element in the `isocortex_metadata.json` . What is the rationale for `"with_descendants": true` in the current code?

I don't know but are you sure that's enough to fix the issue @alTeska mentioned [here](https://github.com/BlueBrain/atlas-placement-hints/issues/12#issuecomment-1742531913)?

**Comment by lecriste** [comment]
I tracked the file in the Atlas pipeline repo:
https://bbpgitlab.epfl.ch/dke/apps/blue_brain_atlas_pipeline/-/blob/develop/metadata/isocortex_metadata.json
Once you agree on the new version, please open an MR there and the pipeline will automatically consume the new file. @rai-pranav

**Comment by rai-pranav** [comment]
Right now, I guess you can update the current pipeline with what @alTeska regex solution. I will test separately , if my solution produces the same result or not.

**Comment by lecriste** [comment]
The placement hints produced with [this version](https://github.com/BlueBrain/atlas-placement-hints/blob/b8c6d3603d57f0e3d3f5320f3c78fffcae336540/atlas_placement_hints/app/metadata/isocortex_metadata.json) of `isocortex_metadata.json` and the new CCFv2022 BBPa annotation are here:
`/gpfs/bbp.cscs.ch/data/project/proj84/atlas_pipeline_runs/2024-05-26T20:43:55+02:00/placement_hints/
`

Let me know if they look good. @alTeska @rai-pranav

**Comment by alTeska** [comment]
I had a look at the new `[PH]y.nrrd`, there is no artefact in this placement hints, approved.

**Comment by lecriste** [comment]
> Was the pipeline rerun w/ this @lecriste? If so, we can work on getting CI to pass, and get it merged.

@mgeplf, it seems we can proceed.

**Review by mgeplf — APPROVED** [review]

**Review by mgeplf — APPROVED** [review]

**Comment by mgeplf** [comment]
Ok, I also did a release: https://github.com/BlueBrain/atlas-placement-hints/releases/tag/v0.1.3

**Pull request merged**
