### PR TITLE
change metadata to ignore barrel cortex in layer placement hints

### PR DESCRIPTION
**Pull request by alTeska**
Accompanying the atlas-commons pull request: 
https://github.com/BlueBrain/atlas-commons/pull/5

Aiming to solve the barrel columns issue:

https://github.com/BlueBrain/atlas-placement-hints/issues/12

### CODE REVIEW

**Comment by lecriste** [comment]
I would assign the `ignore"["name"]` and `ignore["query"]` values by reading the source feathers (as in [here](https://github.com/BlueBrain/atlas-splitter/pull/5/files#diff-253d7bd2e815b71dd6308d48d319492bf56897543a8afe23c45d5b2c690a5a8aR72)), rather than hardcoding them.

**Comment by arnaudon** [comment]
It is really not possible to have this ignore within the main regex? I'm not so versed in regex to know that, but I guess regex should be powerful enough for us to only change it, and not modify the code?

**Comment by alTeska** [comment]
@arnaudon: I tried and I used a little regex to find all of the barrel columns: `"SSp-bfd-[^-]*$"`

but I am unsure how to do this within one regex, please by all means if anyone does let me know :)


@lecriste: I disagree with loading the file, right now the regex provided inside the metadata is used for finding the children of the `SSp-bfd`. So this should work when there are no barrels or when we change the barrels' names as well.

**Comment by arnaudon** [comment]
Just playing with https://regexr.com/ I got for layer1:

Screenshot 2023-10-04 at 11 16 51

something like that should work, no?

**Comment by lecriste** [comment]
> @lecriste: I disagree with loading the file, right now the regex provided inside the metadata is used for finding the children of the `SSp-bfd`. So this should work when there are no barrels or when we change the barrels' names as well.

Yes but the string `"SSp-bfd"` in `"name"` and  in `"query"` is already contained in the feathers file, right?
So instead of repeating it here, we can just read it from the file so if tomorrow we change region in the file, we don't need to change this code.

**Comment by mgeplf** [comment]
Since https://github.com/BlueBrain/atlas-commons/pull/5 was closed, I will close this too.

**Pull request closed without merging**
